/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Applicant;
import org.openapitools.client.model.LoanDetails;
import org.openapitools.client.model.Merchant;
import org.openapitools.client.model.Order;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Represents a loan application
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-10-23T19:03:15.118012600+02:00[Europe/Madrid]", comments = "Generator version: 7.9.0")
public class Application {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private UUID id;

  public static final String SERIALIZED_NAME_APPLICANTS = "applicants";
  @SerializedName(SERIALIZED_NAME_APPLICANTS)
  private List<Applicant> applicants = new ArrayList<>();

  public static final String SERIALIZED_NAME_MERCHANT = "merchant";
  @SerializedName(SERIALIZED_NAME_MERCHANT)
  private Merchant merchant;

  public static final String SERIALIZED_NAME_ORDER = "order";
  @SerializedName(SERIALIZED_NAME_ORDER)
  private Order order;

  public static final String SERIALIZED_NAME_LOAN_DETAILS = "loanDetails";
  @SerializedName(SERIALIZED_NAME_LOAN_DETAILS)
  private LoanDetails loanDetails;

  public static final String SERIALIZED_NAME_SEND_LEAD_EMAIL = "sendLeadEmail";
  @SerializedName(SERIALIZED_NAME_SEND_LEAD_EMAIL)
  private Boolean sendLeadEmail;

  public static final String SERIALIZED_NAME_PHONE_VALIDATION_REQUIRED = "phoneValidationRequired";
  @SerializedName(SERIALIZED_NAME_PHONE_VALIDATION_REQUIRED)
  private Boolean phoneValidationRequired;

  public static final String SERIALIZED_NAME_SIGNATURE_DISABLED = "signatureDisabled";
  @SerializedName(SERIALIZED_NAME_SIGNATURE_DISABLED)
  private Boolean signatureDisabled;

  /**
   * Indicates who is responsible for managing the Application creation and submission
   */
  @JsonAdapter(ManagedByEnum.Adapter.class)
  public enum ManagedByEnum {
    APPLICANT("APPLICANT"),
    
    AGENT("AGENT");

    private String value;

    ManagedByEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ManagedByEnum fromValue(String value) {
      for (ManagedByEnum b : ManagedByEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ManagedByEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ManagedByEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ManagedByEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ManagedByEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ManagedByEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_MANAGED_BY = "managedBy";
  @SerializedName(SERIALIZED_NAME_MANAGED_BY)
  private ManagedByEnum managedBy = ManagedByEnum.AGENT;

  public static final String SERIALIZED_NAME_APPLICATION_TTL_SEC = "applicationTtlSec";
  @SerializedName(SERIALIZED_NAME_APPLICATION_TTL_SEC)
  private Integer applicationTtlSec;

  public static final String SERIALIZED_NAME_SESSION_TTL_SEC = "sessionTtlSec";
  @SerializedName(SERIALIZED_NAME_SESSION_TTL_SEC)
  private Integer sessionTtlSec;

  public static final String SERIALIZED_NAME_PRIMARY_COLOR = "primaryColor";
  @SerializedName(SERIALIZED_NAME_PRIMARY_COLOR)
  private String primaryColor;

  public static final String SERIALIZED_NAME_SHOW_DENIALS = "showDenials";
  @SerializedName(SERIALIZED_NAME_SHOW_DENIALS)
  private Boolean showDenials;

  public static final String SERIALIZED_NAME_IP_ADDRESS = "ipAddress";
  @SerializedName(SERIALIZED_NAME_IP_ADDRESS)
  private String ipAddress;

  public static final String SERIALIZED_NAME_USER_AGENT = "userAgent";
  @SerializedName(SERIALIZED_NAME_USER_AGENT)
  private String userAgent;

  public static final String SERIALIZED_NAME_COMMENTS = "comments";
  @SerializedName(SERIALIZED_NAME_COMMENTS)
  private String comments;

  public Application() {
  }

  public Application id(UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }


  public Application applicants(List<Applicant> applicants) {
    this.applicants = applicants;
    return this;
  }

  public Application addApplicantsItem(Applicant applicantsItem) {
    if (this.applicants == null) {
      this.applicants = new ArrayList<>();
    }
    this.applicants.add(applicantsItem);
    return this;
  }

  /**
   * Represents the collection of applicants who are applying for a loan. At least one applicant is required
   * @return applicants
   */
  @javax.annotation.Nullable
  public List<Applicant> getApplicants() {
    return applicants;
  }

  public void setApplicants(List<Applicant> applicants) {
    this.applicants = applicants;
  }


  public Application merchant(Merchant merchant) {
    this.merchant = merchant;
    return this;
  }

  /**
   * Get merchant
   * @return merchant
   */
  @javax.annotation.Nonnull
  public Merchant getMerchant() {
    return merchant;
  }

  public void setMerchant(Merchant merchant) {
    this.merchant = merchant;
  }


  public Application order(Order order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   */
  @javax.annotation.Nullable
  public Order getOrder() {
    return order;
  }

  public void setOrder(Order order) {
    this.order = order;
  }


  public Application loanDetails(LoanDetails loanDetails) {
    this.loanDetails = loanDetails;
    return this;
  }

  /**
   * Get loanDetails
   * @return loanDetails
   */
  @javax.annotation.Nullable
  public LoanDetails getLoanDetails() {
    return loanDetails;
  }

  public void setLoanDetails(LoanDetails loanDetails) {
    this.loanDetails = loanDetails;
  }


  public Application sendLeadEmail(Boolean sendLeadEmail) {
    this.sendLeadEmail = sendLeadEmail;
    return this;
  }

  /**
   * If the flag is true an email will be sent to the main applicant informing him/her that an Application has been created. Please note that if this flag is set to true,  the MAIN_APPLICANT&#39;s email field should have a valid value. Also, if this flag is true the managedBy field will be set to APPLICANT automatically
   * @return sendLeadEmail
   */
  @javax.annotation.Nullable
  public Boolean getSendLeadEmail() {
    return sendLeadEmail;
  }

  public void setSendLeadEmail(Boolean sendLeadEmail) {
    this.sendLeadEmail = sendLeadEmail;
  }


  public Application phoneValidationRequired(Boolean phoneValidationRequired) {
    this.phoneValidationRequired = phoneValidationRequired;
    return this;
  }

  /**
   * If the flag is false mobile phone validation will be skipped
   * @return phoneValidationRequired
   */
  @javax.annotation.Nullable
  public Boolean getPhoneValidationRequired() {
    return phoneValidationRequired;
  }

  public void setPhoneValidationRequired(Boolean phoneValidationRequired) {
    this.phoneValidationRequired = phoneValidationRequired;
  }


  public Application signatureDisabled(Boolean signatureDisabled) {
    this.signatureDisabled = signatureDisabled;
    return this;
  }

  /**
   * If this flag is true the signature will be disabled until it is set to false
   * @return signatureDisabled
   */
  @javax.annotation.Nullable
  public Boolean getSignatureDisabled() {
    return signatureDisabled;
  }

  public void setSignatureDisabled(Boolean signatureDisabled) {
    this.signatureDisabled = signatureDisabled;
  }


  public Application managedBy(ManagedByEnum managedBy) {
    this.managedBy = managedBy;
    return this;
  }

  /**
   * Indicates who is responsible for managing the Application creation and submission
   * @return managedBy
   */
  @javax.annotation.Nullable
  public ManagedByEnum getManagedBy() {
    return managedBy;
  }

  public void setManagedBy(ManagedByEnum managedBy) {
    this.managedBy = managedBy;
  }


  public Application applicationTtlSec(Integer applicationTtlSec) {
    this.applicationTtlSec = applicationTtlSec;
    return this;
  }

  /**
   * Indicates for how long you as as merchant are willing to keep an application alive in seconds. This value will determine for how long the &#39;token&#39; field will be valid. If this field is not specified and the &#39;managedBy&#39; field is set to APPLICANT, a default value of one week will be assigned
   * @return applicationTtlSec
   */
  @javax.annotation.Nullable
  public Integer getApplicationTtlSec() {
    return applicationTtlSec;
  }

  public void setApplicationTtlSec(Integer applicationTtlSec) {
    this.applicationTtlSec = applicationTtlSec;
  }


  public Application sessionTtlSec(Integer sessionTtlSec) {
    this.sessionTtlSec = sessionTtlSec;
    return this;
  }

  /**
   * Indicates how long the session in Lendismart will last in seconds once you&#39;ve opened the widget via the &#39;openCheckout&#39; method of the JavaScript SDK or you have redirected the user to the applicantUrl. You should try to align the Lendismart session ttl with you own session ttl. Only applies if the &#39;managedBy&#39; field is set to APPLICANT.
   * @return sessionTtlSec
   */
  @javax.annotation.Nullable
  public Integer getSessionTtlSec() {
    return sessionTtlSec;
  }

  public void setSessionTtlSec(Integer sessionTtlSec) {
    this.sessionTtlSec = sessionTtlSec;
  }


  public Application primaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
    return this;
  }

  /**
   * Allows for the customization of the UI color (only applies to applications &#39;managed by applicant&#39;). It should be passed as the color&#39;s hexadecimal code preceded by a #
   * @return primaryColor
   */
  @javax.annotation.Nullable
  public String getPrimaryColor() {
    return primaryColor;
  }

  public void setPrimaryColor(String primaryColor) {
    this.primaryColor = primaryColor;
  }


  public Application showDenials(Boolean showDenials) {
    this.showDenials = showDenials;
    return this;
  }

  /**
   * Indicates if denied offers must be shown to the applicant
   * @return showDenials
   */
  @javax.annotation.Nullable
  public Boolean getShowDenials() {
    return showDenials;
  }

  public void setShowDenials(Boolean showDenials) {
    this.showDenials = showDenials;
  }


  public Application ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * Customer IP address.
   * @return ipAddress
   */
  @javax.annotation.Nullable
  public String getIpAddress() {
    return ipAddress;
  }

  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }


  public Application userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  /**
   * Customer user agent.
   * @return userAgent
   */
  @javax.annotation.Nullable
  public String getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }


  public Application comments(String comments) {
    this.comments = comments;
    return this;
  }

  /**
   * Get comments
   * @return comments
   */
  @javax.annotation.Nullable
  public String getComments() {
    return comments;
  }

  public void setComments(String comments) {
    this.comments = comments;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Application application = (Application) o;
    return Objects.equals(this.id, application.id) &&
        Objects.equals(this.applicants, application.applicants) &&
        Objects.equals(this.merchant, application.merchant) &&
        Objects.equals(this.order, application.order) &&
        Objects.equals(this.loanDetails, application.loanDetails) &&
        Objects.equals(this.sendLeadEmail, application.sendLeadEmail) &&
        Objects.equals(this.phoneValidationRequired, application.phoneValidationRequired) &&
        Objects.equals(this.signatureDisabled, application.signatureDisabled) &&
        Objects.equals(this.managedBy, application.managedBy) &&
        Objects.equals(this.applicationTtlSec, application.applicationTtlSec) &&
        Objects.equals(this.sessionTtlSec, application.sessionTtlSec) &&
        Objects.equals(this.primaryColor, application.primaryColor) &&
        Objects.equals(this.showDenials, application.showDenials) &&
        Objects.equals(this.ipAddress, application.ipAddress) &&
        Objects.equals(this.userAgent, application.userAgent) &&
        Objects.equals(this.comments, application.comments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, applicants, merchant, order, loanDetails, sendLeadEmail, phoneValidationRequired, signatureDisabled, managedBy, applicationTtlSec, sessionTtlSec, primaryColor, showDenials, ipAddress, userAgent, comments);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Application {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    applicants: ").append(toIndentedString(applicants)).append("\n");
    sb.append("    merchant: ").append(toIndentedString(merchant)).append("\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    loanDetails: ").append(toIndentedString(loanDetails)).append("\n");
    sb.append("    sendLeadEmail: ").append(toIndentedString(sendLeadEmail)).append("\n");
    sb.append("    phoneValidationRequired: ").append(toIndentedString(phoneValidationRequired)).append("\n");
    sb.append("    signatureDisabled: ").append(toIndentedString(signatureDisabled)).append("\n");
    sb.append("    managedBy: ").append(toIndentedString(managedBy)).append("\n");
    sb.append("    applicationTtlSec: ").append(toIndentedString(applicationTtlSec)).append("\n");
    sb.append("    sessionTtlSec: ").append(toIndentedString(sessionTtlSec)).append("\n");
    sb.append("    primaryColor: ").append(toIndentedString(primaryColor)).append("\n");
    sb.append("    showDenials: ").append(toIndentedString(showDenials)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    comments: ").append(toIndentedString(comments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("applicants");
    openapiFields.add("merchant");
    openapiFields.add("order");
    openapiFields.add("loanDetails");
    openapiFields.add("sendLeadEmail");
    openapiFields.add("phoneValidationRequired");
    openapiFields.add("signatureDisabled");
    openapiFields.add("managedBy");
    openapiFields.add("applicationTtlSec");
    openapiFields.add("sessionTtlSec");
    openapiFields.add("primaryColor");
    openapiFields.add("showDenials");
    openapiFields.add("ipAddress");
    openapiFields.add("userAgent");
    openapiFields.add("comments");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("merchant");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to Application
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Application.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Application is not found in the empty JSON string", Application.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Application.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Application` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : Application.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (jsonObj.get("applicants") != null && !jsonObj.get("applicants").isJsonNull()) {
        JsonArray jsonArrayapplicants = jsonObj.getAsJsonArray("applicants");
        if (jsonArrayapplicants != null) {
          // ensure the json data is an array
          if (!jsonObj.get("applicants").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `applicants` to be an array in the JSON string but got `%s`", jsonObj.get("applicants").toString()));
          }

          // validate the optional field `applicants` (array)
          for (int i = 0; i < jsonArrayapplicants.size(); i++) {
            Applicant.validateJsonElement(jsonArrayapplicants.get(i));
          };
        }
      }
      // validate the required field `merchant`
      Merchant.validateJsonElement(jsonObj.get("merchant"));
      // validate the optional field `order`
      if (jsonObj.get("order") != null && !jsonObj.get("order").isJsonNull()) {
        Order.validateJsonElement(jsonObj.get("order"));
      }
      // validate the optional field `loanDetails`
      if (jsonObj.get("loanDetails") != null && !jsonObj.get("loanDetails").isJsonNull()) {
        LoanDetails.validateJsonElement(jsonObj.get("loanDetails"));
      }
      if ((jsonObj.get("managedBy") != null && !jsonObj.get("managedBy").isJsonNull()) && !jsonObj.get("managedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `managedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("managedBy").toString()));
      }
      // validate the optional field `managedBy`
      if (jsonObj.get("managedBy") != null && !jsonObj.get("managedBy").isJsonNull()) {
        ManagedByEnum.validateJsonElement(jsonObj.get("managedBy"));
      }
      if ((jsonObj.get("primaryColor") != null && !jsonObj.get("primaryColor").isJsonNull()) && !jsonObj.get("primaryColor").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `primaryColor` to be a primitive type in the JSON string but got `%s`", jsonObj.get("primaryColor").toString()));
      }
      if ((jsonObj.get("ipAddress") != null && !jsonObj.get("ipAddress").isJsonNull()) && !jsonObj.get("ipAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `ipAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipAddress").toString()));
      }
      if ((jsonObj.get("userAgent") != null && !jsonObj.get("userAgent").isJsonNull()) && !jsonObj.get("userAgent").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `userAgent` to be a primitive type in the JSON string but got `%s`", jsonObj.get("userAgent").toString()));
      }
      if ((jsonObj.get("comments") != null && !jsonObj.get("comments").isJsonNull()) && !jsonObj.get("comments").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `comments` to be a primitive type in the JSON string but got `%s`", jsonObj.get("comments").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Application.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Application' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Application> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Application.class));

       return (TypeAdapter<T>) new TypeAdapter<Application>() {
           @Override
           public void write(JsonWriter out, Application value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Application read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of Application given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of Application
   * @throws IOException if the JSON string is invalid with respect to Application
   */
  public static Application fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Application.class);
  }

  /**
   * Convert an instance of Application to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

