/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.ApiLoanSimulationPayload;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.LoanSimulationResponseDTO;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SimulationApi
 */
@Disabled
public class SimulationApiTest {

    private final SimulationApi api = new SimulationApi();

    /**
     * Creates a simulation
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createLoanSimulationTest() throws ApiException {
        ApiLoanSimulationPayload apiLoanSimulationPayload = null;
        LoanSimulationResponseDTO response = api.createLoanSimulation(apiLoanSimulationPayload);
        // TODO: test validations
    }

}
