/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Address
 */
public class AddressTest {
    private final Address model = new Address();

    /**
     * Model tests for Address
     */
    @Test
    public void testAddress() {
        // TODO: test Address
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'streetType'
     */
    @Test
    public void streetTypeTest() {
        // TODO: test streetType
    }

    /**
     * Test the property 'street'
     */
    @Test
    public void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'number'
     */
    @Test
    public void numberTest() {
        // TODO: test number
    }

    /**
     * Test the property 'block'
     */
    @Test
    public void blockTest() {
        // TODO: test block
    }

    /**
     * Test the property 'stairs'
     */
    @Test
    public void stairsTest() {
        // TODO: test stairs
    }

    /**
     * Test the property 'floor'
     */
    @Test
    public void floorTest() {
        // TODO: test floor
    }

    /**
     * Test the property 'door'
     */
    @Test
    public void doorTest() {
        // TODO: test door
    }

    /**
     * Test the property 'complement'
     */
    @Test
    public void complementTest() {
        // TODO: test complement
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'province'
     */
    @Test
    public void provinceTest() {
        // TODO: test province
    }

    /**
     * Test the property 'cityCode'
     */
    @Test
    public void cityCodeTest() {
        // TODO: test cityCode
    }

    /**
     * Test the property 'localityCode'
     */
    @Test
    public void localityCodeTest() {
        // TODO: test localityCode
    }

    /**
     * Test the property 'countryIso'
     */
    @Test
    public void countryIsoTest() {
        // TODO: test countryIso
    }

    /**
     * Test the property 'fullAddress'
     */
    @Test
    public void fullAddressTest() {
        // TODO: test fullAddress
    }

    /**
     * Test the property 'line1'
     */
    @Test
    public void line1Test() {
        // TODO: test line1
    }

    /**
     * Test the property 'line2'
     */
    @Test
    public void line2Test() {
        // TODO: test line2
    }

    /**
     * Test the property 'cityName'
     */
    @Test
    public void cityNameTest() {
        // TODO: test cityName
    }

    /**
     * Test the property 'provinceName'
     */
    @Test
    public void provinceNameTest() {
        // TODO: test provinceName
    }

}
