/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.LinkedHashSet;
import java.util.Set;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiLoanSimulationPayload
 */
public class ApiLoanSimulationPayloadTest {
    private final ApiLoanSimulationPayload model = new ApiLoanSimulationPayload();

    /**
     * Model tests for ApiLoanSimulationPayload
     */
    @Test
    public void testApiLoanSimulationPayload() {
        // TODO: test ApiLoanSimulationPayload
    }

    /**
     * Test the property 'merchantCode'
     */
    @Test
    public void merchantCodeTest() {
        // TODO: test merchantCode
    }

    /**
     * Test the property 'goodsTypeCode'
     */
    @Test
    public void goodsTypeCodeTest() {
        // TODO: test goodsTypeCode
    }

    /**
     * Test the property 'purchaseAmount'
     */
    @Test
    public void purchaseAmountTest() {
        // TODO: test purchaseAmount
    }

    /**
     * Test the property 'requestedAmount'
     */
    @Test
    public void requestedAmountTest() {
        // TODO: test requestedAmount
    }

    /**
     * Test the property 'applicantType'
     */
    @Test
    public void applicantTypeTest() {
        // TODO: test applicantType
    }

    /**
     * Test the property 'maxMonthlyPayment'
     */
    @Test
    public void maxMonthlyPaymentTest() {
        // TODO: test maxMonthlyPayment
    }

    /**
     * Test the property 'subscriptionPayment'
     */
    @Test
    public void subscriptionPaymentTest() {
        // TODO: test subscriptionPayment
    }

    /**
     * Test the property 'maxNominalAnnualRate'
     */
    @Test
    public void maxNominalAnnualRateTest() {
        // TODO: test maxNominalAnnualRate
    }

    /**
     * Test the property 'productType'
     */
    @Test
    public void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'paymentFrequency'
     */
    @Test
    public void paymentFrequencyTest() {
        // TODO: test paymentFrequency
    }

    /**
     * Test the property 'instalmentType'
     */
    @Test
    public void instalmentTypeTest() {
        // TODO: test instalmentType
    }

    /**
     * Test the property 'vehicleMake'
     */
    @Test
    public void vehicleMakeTest() {
        // TODO: test vehicleMake
    }

    /**
     * Test the property 'vehicleModelCode'
     */
    @Test
    public void vehicleModelCodeTest() {
        // TODO: test vehicleModelCode
    }

    /**
     * Test the property 'vehicleVersionCode'
     */
    @Test
    public void vehicleVersionCodeTest() {
        // TODO: test vehicleVersionCode
    }

    /**
     * Test the property 'registrationNumber'
     */
    @Test
    public void registrationNumberTest() {
        // TODO: test registrationNumber
    }

    /**
     * Test the property 'firstRegistrationDate'
     */
    @Test
    public void firstRegistrationDateTest() {
        // TODO: test firstRegistrationDate
    }

    /**
     * Test the property 'mileage'
     */
    @Test
    public void mileageTest() {
        // TODO: test mileage
    }

    /**
     * Test the property 'serviceDuration'
     */
    @Test
    public void serviceDurationTest() {
        // TODO: test serviceDuration
    }

    /**
     * Test the property 'lender'
     */
    @Test
    public void lenderTest() {
        // TODO: test lender
    }

    /**
     * Test the property 'feePaymentType'
     */
    @Test
    public void feePaymentTypeTest() {
        // TODO: test feePaymentType
    }

    /**
     * Test the property 'term'
     */
    @Test
    public void termTest() {
        // TODO: test term
    }

    /**
     * Test the property 'gracePeriod'
     */
    @Test
    public void gracePeriodTest() {
        // TODO: test gracePeriod
    }

    /**
     * Test the property 'maxMerchantCost'
     */
    @Test
    public void maxMerchantCostTest() {
        // TODO: test maxMerchantCost
    }

    /**
     * Test the property 'maxMerchantCostPct'
     */
    @Test
    public void maxMerchantCostPctTest() {
        // TODO: test maxMerchantCostPct
    }

    /**
     * Test the property 'maxNir'
     */
    @Test
    public void maxNirTest() {
        // TODO: test maxNir
    }

    /**
     * Test the property 'openingFeePct'
     */
    @Test
    public void openingFeePctTest() {
        // TODO: test openingFeePct
    }

    /**
     * Test the property 'withInsurance'
     */
    @Test
    public void withInsuranceTest() {
        // TODO: test withInsurance
    }

    /**
     * Test the property 'paymentPeriodStartDate'
     */
    @Test
    public void paymentPeriodStartDateTest() {
        // TODO: test paymentPeriodStartDate
    }

    /**
     * Test the property 'mainApplicantBirthDate'
     */
    @Test
    public void mainApplicantBirthDateTest() {
        // TODO: test mainApplicantBirthDate
    }

    /**
     * Test the property 'drivingLicenceIssuanceDate'
     */
    @Test
    public void drivingLicenceIssuanceDateTest() {
        // TODO: test drivingLicenceIssuanceDate
    }

    /**
     * Test the property 'postalCode'
     */
    @Test
    public void postalCodeTest() {
        // TODO: test postalCode
    }

    /**
     * Test the property 'occupation'
     */
    @Test
    public void occupationTest() {
        // TODO: test occupation
    }

    /**
     * Test the property 'insuranceCoverages'
     */
    @Test
    public void insuranceCoveragesTest() {
        // TODO: test insuranceCoverages
    }

    /**
     * Test the property 'languageTag'
     */
    @Test
    public void languageTagTest() {
        // TODO: test languageTag
    }

}
