/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.client.model.Address;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Applicant
 */
public class ApplicantTest {
    private final Applicant model = new Applicant();

    /**
     * Model tests for Applicant
     */
    @Test
    public void testApplicant() {
        // TODO: test Applicant
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'role'
     */
    @Test
    public void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'relationship'
     */
    @Test
    public void relationshipTest() {
        // TODO: test relationship
    }

    /**
     * Test the property 'docIdType'
     */
    @Test
    public void docIdTypeTest() {
        // TODO: test docIdType
    }

    /**
     * Test the property 'docIdType2'
     */
    @Test
    public void docIdType2Test() {
        // TODO: test docIdType2
    }

    /**
     * Test the property 'docIdNumber'
     */
    @Test
    public void docIdNumberTest() {
        // TODO: test docIdNumber
    }

    /**
     * Test the property 'docIdNumber2'
     */
    @Test
    public void docIdNumber2Test() {
        // TODO: test docIdNumber2
    }

    /**
     * Test the property 'docIdExpirationDate'
     */
    @Test
    public void docIdExpirationDateTest() {
        // TODO: test docIdExpirationDate
    }

    /**
     * Test the property 'drivingLicenceIssuanceDate'
     */
    @Test
    public void drivingLicenceIssuanceDateTest() {
        // TODO: test drivingLicenceIssuanceDate
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'firstName'
     */
    @Test
    public void firstNameTest() {
        // TODO: test firstName
    }

    /**
     * Test the property 'surname1'
     */
    @Test
    public void surname1Test() {
        // TODO: test surname1
    }

    /**
     * Test the property 'surname2'
     */
    @Test
    public void surname2Test() {
        // TODO: test surname2
    }

    /**
     * Test the property 'birthDate'
     */
    @Test
    public void birthDateTest() {
        // TODO: test birthDate
    }

    /**
     * Test the property 'nationalityIso'
     */
    @Test
    public void nationalityIsoTest() {
        // TODO: test nationalityIso
    }

    /**
     * Test the property 'nationality2Iso'
     */
    @Test
    public void nationality2IsoTest() {
        // TODO: test nationality2Iso
    }

    /**
     * Test the property 'paymentMethod'
     */
    @Test
    public void paymentMethodTest() {
        // TODO: test paymentMethod
    }

    /**
     * Test the property 'cardNumber'
     */
    @Test
    public void cardNumberTest() {
        // TODO: test cardNumber
    }

    /**
     * Test the property 'accountNumber'
     */
    @Test
    public void accountNumberTest() {
        // TODO: test accountNumber
    }

    /**
     * Test the property 'accountCreationDate'
     */
    @Test
    public void accountCreationDateTest() {
        // TODO: test accountCreationDate
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'socialSecurityNumber'
     */
    @Test
    public void socialSecurityNumberTest() {
        // TODO: test socialSecurityNumber
    }

    /**
     * Test the property 'phoneType1'
     */
    @Test
    public void phoneType1Test() {
        // TODO: test phoneType1
    }

    /**
     * Test the property 'phone1'
     */
    @Test
    public void phone1Test() {
        // TODO: test phone1
    }

    /**
     * Test the property 'phoneType2'
     */
    @Test
    public void phoneType2Test() {
        // TODO: test phoneType2
    }

    /**
     * Test the property 'phone2'
     */
    @Test
    public void phone2Test() {
        // TODO: test phone2
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'residencyStartDate'
     */
    @Test
    public void residencyStartDateTest() {
        // TODO: test residencyStartDate
    }

    /**
     * Test the property 'residencyEndDate'
     */
    @Test
    public void residencyEndDateTest() {
        // TODO: test residencyEndDate
    }

    /**
     * Test the property 'nativeAddress'
     */
    @Test
    public void nativeAddressTest() {
        // TODO: test nativeAddress
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'maritalStatus'
     */
    @Test
    public void maritalStatusTest() {
        // TODO: test maritalStatus
    }

    /**
     * Test the property 'dependent'
     */
    @Test
    public void dependentTest() {
        // TODO: test dependent
    }

    /**
     * Test the property 'housingTenureType'
     */
    @Test
    public void housingTenureTypeTest() {
        // TODO: test housingTenureType
    }

    /**
     * Test the property 'housingTenureStartDate'
     */
    @Test
    public void housingTenureStartDateTest() {
        // TODO: test housingTenureStartDate
    }

    /**
     * Test the property 'housingExpenses'
     */
    @Test
    public void housingExpensesTest() {
        // TODO: test housingExpenses
    }

    /**
     * Test the property 'otherExpenses'
     */
    @Test
    public void otherExpensesTest() {
        // TODO: test otherExpenses
    }

    /**
     * Test the property 'occupationType'
     */
    @Test
    public void occupationTypeTest() {
        // TODO: test occupationType
    }

    /**
     * Test the property 'occupation'
     */
    @Test
    public void occupationTest() {
        // TODO: test occupation
    }

    /**
     * Test the property 'profession'
     */
    @Test
    public void professionTest() {
        // TODO: test profession
    }

    /**
     * Test the property 'jobTitle'
     */
    @Test
    public void jobTitleTest() {
        // TODO: test jobTitle
    }

    /**
     * Test the property 'industryType'
     */
    @Test
    public void industryTypeTest() {
        // TODO: test industryType
    }

    /**
     * Test the property 'industry'
     */
    @Test
    public void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'contractStartDate'
     */
    @Test
    public void contractStartDateTest() {
        // TODO: test contractStartDate
    }

    /**
     * Test the property 'contractEndDate'
     */
    @Test
    public void contractEndDateTest() {
        // TODO: test contractEndDate
    }

    /**
     * Test the property 'companyIdNumber'
     */
    @Test
    public void companyIdNumberTest() {
        // TODO: test companyIdNumber
    }

    /**
     * Test the property 'companyPhone'
     */
    @Test
    public void companyPhoneTest() {
        // TODO: test companyPhone
    }

    /**
     * Test the property 'companyName'
     */
    @Test
    public void companyNameTest() {
        // TODO: test companyName
    }

    /**
     * Test the property 'companyAddress'
     */
    @Test
    public void companyAddressTest() {
        // TODO: test companyAddress
    }

    /**
     * Test the property 'monthlyIncome'
     */
    @Test
    public void monthlyIncomeTest() {
        // TODO: test monthlyIncome
    }

    /**
     * Test the property 'incomeFrequency'
     */
    @Test
    public void incomeFrequencyTest() {
        // TODO: test incomeFrequency
    }

    /**
     * Test the property 'consentGroup'
     */
    @Test
    public void consentGroupTest() {
        // TODO: test consentGroup
    }

}
