/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for LoanDetails
 */
public class LoanDetailsTest {
    private final LoanDetails model = new LoanDetails();

    /**
     * Model tests for LoanDetails
     */
    @Test
    public void testLoanDetails() {
        // TODO: test LoanDetails
    }

    /**
     * Test the property 'requestedAmount'
     */
    @Test
    public void requestedAmountTest() {
        // TODO: test requestedAmount
    }

    /**
     * Test the property 'maxMonthlyPayment'
     */
    @Test
    public void maxMonthlyPaymentTest() {
        // TODO: test maxMonthlyPayment
    }

    /**
     * Test the property 'term'
     */
    @Test
    public void termTest() {
        // TODO: test term
    }

    /**
     * Test the property 'financingPromotion'
     */
    @Test
    public void financingPromotionTest() {
        // TODO: test financingPromotion
    }

    /**
     * Test the property 'productType'
     */
    @Test
    public void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'openingFeePct'
     */
    @Test
    public void openingFeePctTest() {
        // TODO: test openingFeePct
    }

    /**
     * Test the property 'maxNir'
     */
    @Test
    public void maxNirTest() {
        // TODO: test maxNir
    }

    /**
     * Test the property 'feePaymentType'
     */
    @Test
    public void feePaymentTypeTest() {
        // TODO: test feePaymentType
    }

    /**
     * Test the property 'gracePeriod'
     */
    @Test
    public void gracePeriodTest() {
        // TODO: test gracePeriod
    }

    /**
     * Test the property 'monthlyDueDate'
     */
    @Test
    public void monthlyDueDateTest() {
        // TODO: test monthlyDueDate
    }

    /**
     * Test the property 'insurance'
     */
    @Test
    public void insuranceTest() {
        // TODO: test insurance
    }

    /**
     * Test the property 'noAccount'
     */
    @Test
    public void noAccountTest() {
        // TODO: test noAccount
    }

    /**
     * Test the property 'applicantType'
     */
    @Test
    public void applicantTypeTest() {
        // TODO: test applicantType
    }

    /**
     * Test the property 'maxMerchantCost'
     */
    @Test
    public void maxMerchantCostTest() {
        // TODO: test maxMerchantCost
    }

    /**
     * Test the property 'maxMerchantCostPct'
     */
    @Test
    public void maxMerchantCostPctTest() {
        // TODO: test maxMerchantCostPct
    }

}
