/*
 * Lendismart API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Vehicle
 */
public class VehicleTest {
    private final Vehicle model = new Vehicle();

    /**
     * Model tests for Vehicle
     */
    @Test
    public void testVehicle() {
        // TODO: test Vehicle
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'subtype'
     */
    @Test
    public void subtypeTest() {
        // TODO: test subtype
    }

    /**
     * Test the property 'make'
     */
    @Test
    public void makeTest() {
        // TODO: test make
    }

    /**
     * Test the property 'registrationNumber'
     */
    @Test
    public void registrationNumberTest() {
        // TODO: test registrationNumber
    }

    /**
     * Test the property 'firstRegistrationDate'
     */
    @Test
    public void firstRegistrationDateTest() {
        // TODO: test firstRegistrationDate
    }

    /**
     * Test the property 'vin'
     */
    @Test
    public void vinTest() {
        // TODO: test vin
    }

    /**
     * Test the property 'mileage'
     */
    @Test
    public void mileageTest() {
        // TODO: test mileage
    }

    /**
     * Test the property 'versionCode'
     */
    @Test
    public void versionCodeTest() {
        // TODO: test versionCode
    }

    /**
     * Test the property 'reregistered'
     */
    @Test
    public void reregisteredTest() {
        // TODO: test reregistered
    }

}
